import fs from 'node:fs';
import path from 'node:path';
import { getPkgVersion } from '../../utils.js';
import type { InstallResult } from './types.js';

export function installGatewayConfig(targetDir: string, dryRun: boolean): InstallResult[] {
  const PKG_VERSION = getPkgVersion();
  const reagentDir = path.join(targetDir, '.reagent');
  const gatewayPath = path.join(reagentDir, 'gateway.yaml');

  // Idempotent: skip if gateway.yaml already exists
  if (fs.existsSync(gatewayPath)) {
    return [{ file: '.reagent/gateway.yaml', status: 'skipped' }];
  }

  if (!dryRun) {
    fs.mkdirSync(reagentDir, { recursive: true });
    const content = `# .reagent/gateway.yaml — generated by @bookedsolid/reagent v${PKG_VERSION}
# Defines downstream MCP servers that reagent proxies through its middleware chain.
#
# Usage:
#   reagent serve
#
# Each server entry spawns a child process and communicates over stdio MCP.
# Tool names are namespaced as: <server-name>__<tool-name>
#
# Tier classification (convention-based, overridable):
#   read:        get_*, list_*, search_*, query_*, read_*, fetch_*, check_*, health_*, describe_*, show_*, count_*
#   destructive: delete_*, drop_*, purge_*, remove_*, destroy_*, ban_*, kick_*, revoke_*, truncate_*
#   write:       everything else (default)

version: "1"

# To add a server, replace "servers: {}" with:
#
# servers:
#   my-server:
#     command: npx
#     args: ['-y', 'my-mcp-server@latest']
#     env:
#       API_KEY: '\${MY_API_KEY}'
#     tool_overrides:
#       dangerous_action:
#         tier: destructive
#       admin_delete:
#         tier: destructive
#         blocked: true

servers: {}
`;
    fs.writeFileSync(gatewayPath, content, 'utf8');
  }

  return [{ file: '.reagent/gateway.yaml', status: 'installed' }];
}
