import fs from 'node:fs';
import path from 'node:path';
import { getPkgVersion } from '../../utils.js';
import type { InstallResult, ProfileConfig } from './types.js';

export function installPolicy(
  targetDir: string,
  profileName: string,
  profile: ProfileConfig,
  dryRun: boolean,
  techProfile?: string
): InstallResult[] {
  const PKG_VERSION = getPkgVersion();
  const reagentDir = path.join(targetDir, '.reagent');
  const policyPath = path.join(reagentDir, 'policy.yaml');

  if (fs.existsSync(policyPath)) {
    return [{ file: '.reagent/policy.yaml', status: 'skipped' }];
  }

  if (!dryRun) {
    fs.mkdirSync(reagentDir, { recursive: true });
    const now = new Date().toISOString();
    const blockAttribution = profile.blockAiAttribution === true;
    const disclosureMode = profile.security?.disclosureMode ?? 'advisory';
    const coverageEnabled = profile.coverage?.enabled === true;
    const coverageThreshold = profile.coverage?.threshold ?? 80;
    const blockedPaths = profile.blockedPaths ?? [
      '.reagent/policy.yaml',
      '.reagent/HALT',
      '.github/workflows/',
      '.env',
      '.env.*',
    ];
    const blockedPathsYaml = blockedPaths.length
      ? '\n' + blockedPaths.map((p: string) => `  - "${p}"`).join('\n')
      : ' []';
    const content = `# .reagent/policy.yaml — generated by @bookedsolid/reagent v${PKG_VERSION}
# Commit this file. Edit autonomy_level and max_autonomy_level as needed.
# Run 'reagent freeze --reason "..."' to halt all agent operations.

version: "1"
profile: "${profileName}"
${techProfile ? `tech_profile: "${techProfile}"\n` : ''}installed_by: "reagent@${PKG_VERSION}"
installed_at: "${now}"

# Autonomy levels:
#   L0 — Read-only; every write requires explicit user approval
#   L1 — Writes allowed to non-blocked paths; destructive operations blocked
#   L2 — Writes + PR creation allowed; destructive tier blocked
#   L3 — All writes allowed; advisory on anomalous patterns
autonomy_level: L1
max_autonomy_level: L2

# Human must approve any autonomy level increase
promotion_requires_human_approval: true

# Block AI attribution in commits and PRs (opt-in)
# When true, the commit-msg hook rejects commits containing AI attribution
# markers (Co-Authored-By, "Generated with [Tool]", etc.) and the
# attribution-advisory hook blocks gh pr create/edit commands with attribution.
# Casual mentions of AI tools in commit messages are still allowed.
block_ai_attribution: ${blockAttribution}

# Paths hooks and agents must never modify
blocked_paths:${blockedPathsYaml}

# Optional: Discord webhook for halt/promote notifications
notification_channel: ""

# Coverage quality gate (opt-in)
# When enabled, the pre-push hook enforces minimum test coverage before push.
# Requires @vitest/coverage-v8 (or equivalent) installed in the project.
#   enabled   — set to true to activate the gate
#   threshold — minimum percentage for lines, functions, and statements
#               branches threshold is automatically set to threshold - 10
coverage:
  enabled: ${coverageEnabled}
  threshold: ${coverageThreshold}

# Security disclosure configuration
# Controls how the security-disclosure-gate hook routes security findings:
#   advisory — public OSS repos: redirect to GitHub Security Advisories (default)
#   issues   — private client repos: redirect to labeled internal issue queue
#   disabled — no gate (not recommended)
security:
  disclosure_mode: "${disclosureMode}"

# Context protection — commands that must run in subagents, never in coordinator
# The dangerous-bash-interceptor hook blocks these commands when run directly.
# Prevents context window exhaustion from verbose test/build output.
context_protection:
  delegate_to_subagent:
    - "pnpm run preflight"
    - "pnpm run test"
    - "pnpm run build"
  max_bash_output_lines: 100
`;
    fs.writeFileSync(policyPath, content, 'utf8');
  }

  return [{ file: '.reagent/policy.yaml', status: 'installed' }];
}
